MCSC 6020 G - FINAL PROJECT

TO RUN CODE:
- IMPORT PROJECT INTO IDE
- OPEN: 
	<NormalResiduals.py>,
	<Non-NormalResiduals.py>, or 
	<Non-NormalResiduals_Transformations.py>
- ENSURE ALL IMPORT LIBRARIES ARE INSTALLED
- SELECT RUN FROM MENU

ALTERNATIVELY:
- RUN FROM TERMINAL SINCE APPARENTLY THAT'S
  BEEN WORKING SO FAR

NOTES:
- REPORT OUTSIDE OF PROJECT <venv> FOLDER
- PRESENTATION OUTSIDE OF PROJECT <venv> FOLDER
